# Generated by Django 5.0.9 on 2026-08-22 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.CharField(blank=True, max_length=40)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "activity categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("SIGHTSEEING", "Sightseeing"),
                            ("FOOD", "Food & Dining"),
                            ("ADVENTURE", "Adventure"),
                            ("CULTURE", "Culture & Heritage"),
                            ("NIGHTLIFE", "Nightlife"),
                            ("SHOPPING", "Shopping"),
                            ("NATURE", "Nature & Outdoors"),
                            ("RELAX", "Relaxation"),
                            ("TRANSPORT", "Transport"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("image_url", models.URLField(blank=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=2),
                ),
                (
                    "popularity_score",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means generic — available in any city.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="geo.city",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="activities.activitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activities",
                "ordering": ("-popularity_score", "name"),
                "indexes": [
                    models.Index(
                        fields=["city", "activity_type"], name="activity_city_type_idx"
                    ),
                    models.Index(
                        fields=["-popularity_score"], name="activity_popularity_idx"
                    ),
                ],
            },
        ),
    ]
