# Generated by Django 5.0.9 on 2026-08-22 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('geo', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_stops', to='geo.city')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('custom_title', models.CharField(blank=True, max_length=150)),
                ('day_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_activities', to='activities.activity')),
                ('trip_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trips.tripstop')),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='tripstop',
            index=models.Index(fields=['trip', 'order'], name='tripstop_trip_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='tripstop_end_date_gte_start_date'),
        ),
        migrations.AddIndex(
            model_name='tripactivity',
            index=models.Index(fields=['trip_stop', 'day_date', 'order'], name='tripactivity_day_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripactivity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('activity__isnull', False), ('custom_title', '')), models.Q(('activity__isnull', True), models.Q(('custom_title', ''), _negated=True)), _connector='OR'), name='tripactivity_catalog_xor_custom'),
        ),
    ]
