# Generated by Django 5.0.9 on 2026-08-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0002_tripstop_tripactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('TRANSPORT', 'Transport'), ('STAY', 'Stay'), ('ACTIVITY', 'Activities'), ('MEALS', 'Meals'), ('SHOPPING', 'Shopping'), ('OTHER', 'Other')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('incurred_on', models.DateField(blank=True, null=True)),
                ('is_estimated', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip')),
                ('trip_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='trips.tripstop')),
            ],
            options={
                'ordering': ('-incurred_on', '-created_at'),
                'indexes': [models.Index(fields=['trip', 'category'], name='expense_trip_category_idx'), models.Index(fields=['trip', 'incurred_on'], name='expense_trip_day_idx')],
            },
        ),
    ]
