# Generated by Django 5.2.17 on 2026-08-22 05:33

import autoslug.fields
import cities_light.abstract_models
import cities_light.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('name_ascii', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='ASCII name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name_ascii', verbose_name='slug')),
                ('geoname_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Geonames ID')),
                ('alternate_names', models.TextField(blank=True, default='', null=True, verbose_name='alternate names')),
                ('translations', models.JSONField(blank=True, default=dict, verbose_name='translations')),
                ('code2', models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='ISO 3166-1 alpha-2')),
                ('code3', models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='ISO 3166-1 alpha-3')),
                ('continent', models.CharField(choices=[('OC', 'Oceania'), ('EU', 'Europe'), ('AF', 'Africa'), ('NA', 'North America'), ('AN', 'Antarctica'), ('SA', 'South America'), ('AS', 'Asia')], db_index=True, max_length=2, verbose_name='continent')),
                ('tld', models.CharField(blank=True, db_index=True, max_length=5, verbose_name='top-level domain')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone code')),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('name_ascii', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='ASCII name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name_ascii', verbose_name='slug')),
                ('geoname_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Geonames ID')),
                ('alternate_names', models.TextField(blank=True, default='', null=True, verbose_name='alternate names')),
                ('translations', models.JSONField(blank=True, default=dict, verbose_name='translations')),
                ('display_name', models.CharField(max_length=200, verbose_name='display name')),
                ('geoname_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Geonames code')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'region/state',
                'verbose_name_plural': 'regions/states',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('country', 'name'), ('country', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('name_ascii', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='ASCII name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name_ascii', verbose_name='slug')),
                ('geoname_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Geonames ID')),
                ('alternate_names', models.TextField(blank=True, default='', null=True, verbose_name='alternate names')),
                ('translations', models.JSONField(blank=True, default=dict, verbose_name='translations')),
                ('display_name', models.CharField(max_length=200, verbose_name='display name')),
                ('geoname_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Geonames code')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.country', verbose_name='country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.region', verbose_name='region')),
            ],
            options={
                'verbose_name': 'SubRegion',
                'verbose_name_plural': 'SubRegions',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('name_ascii', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='ASCII name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name_ascii', verbose_name='slug')),
                ('geoname_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Geonames ID')),
                ('alternate_names', models.TextField(blank=True, default='', null=True, verbose_name='alternate names')),
                ('translations', models.JSONField(blank=True, default=dict, verbose_name='translations')),
                ('display_name', models.CharField(max_length=200, verbose_name='display name')),
                ('search_names', cities_light.abstract_models.ToSearchTextField(blank=True, db_index=True, default='', max_length=4000, verbose_name='search names')),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='longitude')),
                ('population', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='population')),
                ('feature_code', models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='feature code')),
                ('timezone', models.CharField(blank=True, db_index=True, max_length=40, null=True, validators=[cities_light.validators.timezone_validator], verbose_name='timezone')),
                ('cost_index', models.DecimalField(blank=True, decimal_places=1, help_text='Daily-budget tier from 1.0 (cheap) to 5.0 (expensive). Null for cities outside the curated set.', max_digits=4, null=True)),
                ('popularity', models.PositiveIntegerField(db_index=True, default=0, help_text='Trip stops referencing this city; set by refresh_popularity.')),
                ('blurb', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='cities/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.country', verbose_name='country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.region', verbose_name='region')),
                ('subregion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.subregion', verbose_name='subregion')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('region', 'subregion', 'name'), ('region', 'subregion', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('category', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('food', 'Food & drink'), ('adventure', 'Adventure'), ('culture', 'Culture'), ('nightlife', 'Nightlife'), ('shopping', 'Shopping'), ('nature', 'Nature'), ('wellness', 'Wellness')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost per person.', max_digits=9)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('image', models.ImageField(blank=True, upload_to='activities/')),
                ('popularity', models.PositiveIntegerField(db_index=True, default=0, help_text='Times added to an itinerary; set by refresh_popularity.')),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='geo.city')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city', 'category'], name='geo_activit_city_id_2730d0_idx')],
                'constraints': [models.UniqueConstraint(fields=('city', 'slug'), name='uniq_activity_city_slug')],
            },
        ),
    ]
