import type { Trip } from "@/lib/types";

export const trips: Trip[] = [
  {
    id: "kerala-backwaters",
    title: "Kerala Backwaters",
    city: "Alleppey",
    country: "India",
    startDate: "2026-08-18",
    endDate: "2026-08-26",
    budget: 64000,
    stops: 4,
    status: "ongoing",
    cover: "forest",
  },
  {
    id: "tokyo-autumn",
    title: "Tokyo in Autumn",
    city: "Tokyo",
    country: "Japan",
    startDate: "2026-10-04",
    endDate: "2026-10-14",
    budget: 210000,
    stops: 6,
    status: "upcoming",
    cover: "dusk",
  },
  {
    id: "rajasthan-loop",
    title: "Rajasthan Heritage Loop",
    city: "Jaipur",
    country: "India",
    startDate: "2026-12-20",
    endDate: "2026-12-30",
    budget: 88000,
    stops: 5,
    status: "upcoming",
    cover: "sunset",
  },
  {
    id: "bali-reset",
    title: "Bali Reset",
    city: "Ubud",
    country: "Indonesia",
    startDate: "2026-03-02",
    endDate: "2026-03-11",
    budget: 132000,
    stops: 3,
    status: "completed",
    cover: "ocean",
  },
  {
    id: "leh-ladakh",
    title: "Leh–Ladakh Ride",
    city: "Leh",
    country: "India",
    startDate: "2025-06-12",
    endDate: "2025-06-22",
    budget: 74000,
    stops: 7,
    status: "completed",
    cover: "ocean",
  },
];

export const tripsByStatus = {
  ongoing: trips.filter((trip) => trip.status === "ongoing"),
  upcoming: trips.filter((trip) => trip.status === "upcoming"),
  completed: trips.filter((trip) => trip.status === "completed"),
};
