import type { Region, Suggestion, Trip } from "@/lib/types";

export const regions: Region[] = [
  {
    id: "himalayan-north",
    name: "Himalayan North",
    country: "India",
    blurb: "High passes, monasteries and very cold mornings",
    tripCount: 128,
    fromPrice: 32000,
    cover: "ocean",
  },
  {
    id: "kerala",
    name: "Kerala Backwaters",
    country: "India",
    blurb: "Houseboats, coconut groves and slow afternoons",
    tripCount: 96,
    fromPrice: 28000,
    cover: "forest",
  },
  {
    id: "rajasthan",
    name: "Rajasthan",
    country: "India",
    blurb: "Forts, step wells and desert sunsets",
    tripCount: 143,
    fromPrice: 24000,
    cover: "sunset",
  },
  {
    id: "japan",
    name: "Japan",
    country: "Japan",
    blurb: "Bullet trains, temple towns and autumn colour",
    tripCount: 71,
    fromPrice: 165000,
    cover: "dusk",
  },
  {
    id: "bali",
    name: "Bali & Nusa Islands",
    country: "Indonesia",
    blurb: "Rice terraces, reef dives and warm evenings",
    tripCount: 88,
    fromPrice: 74000,
    cover: "ocean",
  },
  {
    id: "swiss-alps",
    name: "Swiss Alps",
    country: "Switzerland",
    blurb: "Cable cars, lake towns and long ridge walks",
    tripCount: 54,
    fromPrice: 210000,
    cover: "dusk",
  },
];

export const trips: Trip[] = [
  {
    id: "kerala-backwaters",
    title: "Kerala Backwaters",
    city: "Alleppey",
    country: "India",
    startDate: "2026-08-18",
    endDate: "2026-08-26",
    budget: 64000,
    stops: 4,
    status: "ongoing",
    cover: "forest",
  },
  {
    id: "tokyo-autumn",
    title: "Tokyo in Autumn",
    city: "Tokyo",
    country: "Japan",
    startDate: "2026-10-04",
    endDate: "2026-10-14",
    budget: 210000,
    stops: 6,
    status: "upcoming",
    cover: "dusk",
  },
  {
    id: "rajasthan-loop",
    title: "Rajasthan Heritage Loop",
    city: "Jaipur",
    country: "India",
    startDate: "2026-12-20",
    endDate: "2026-12-30",
    budget: 88000,
    stops: 5,
    status: "upcoming",
    cover: "sunset",
  },
  {
    id: "bali-reset",
    title: "Bali Reset",
    city: "Ubud",
    country: "Indonesia",
    startDate: "2026-03-02",
    endDate: "2026-03-11",
    budget: 132000,
    stops: 3,
    status: "completed",
    cover: "ocean",
  },
  {
    id: "leh-ladakh",
    title: "Leh–Ladakh Ride",
    city: "Leh",
    country: "India",
    startDate: "2025-06-12",
    endDate: "2025-06-22",
    budget: 74000,
    stops: 7,
    status: "completed",
    cover: "ocean",
  },
];

export const suggestions: Suggestion[] = [
  { id: "old-town-walk", label: "Old town walking tour", kind: "activity" },
  { id: "sunset-viewpoint", label: "Sunset viewpoint", kind: "place" },
  { id: "local-food-market", label: "Local food market", kind: "place" },
  { id: "heritage-museum", label: "Heritage museum", kind: "activity" },
  { id: "evening-boat-ride", label: "Evening boat ride", kind: "activity" },
  { id: "nearby-hiking-trail", label: "Nearby hiking trail", kind: "place" },
  { id: "street-food-crawl", label: "Street food crawl", kind: "activity" },
  { id: "sunrise-viewpoint", label: "Sunrise viewpoint", kind: "place" },
];

export const tripsByStatus = {
  ongoing: trips.filter((trip) => trip.status === "ongoing"),
  upcoming: trips.filter((trip) => trip.status === "upcoming"),
  completed: trips.filter((trip) => trip.status === "completed"),
};
